#include <GamepadConfig.h>

#define PIN_DPAD_UP     13
#define PIN_DPAD_DOWN   12
#define PIN_DPAD_LEFT   GAMEPAD_MASK_LEFT
#define PIN_DPAD_RIGHT  GAMEPAD_MASK_RIGHT
#define PIN_BUTTON_B1   0
#define PIN_BUTTON_B2   1
#define PIN_BUTTON_B3   2
#define PIN_BUTTON_B4   3
#define PIN_BUTTON_L1   4
#define PIN_BUTTON_R2   26
#define PIN_BUTTON_S1   11
#define PIN_BUTTON_S2   10
#define PIN_BUTTON_R1   GAMEPAD_MASK_R1
#define PIN_BUTTON_L2   GAMEPAD_MASK_L2
#define PIN_BUTTON_L3   GAMEPAD_MASK_L3
#define PIN_BUTTON_R3   GAMEPAD_MASK_R3
#define PIN_BUTTON_A1   GAMEPAD_MASK_A1
#define PIN_BUTTON_A2   GAMEPAD_MASK_A2